### ISSUE TITLE
Bug in setting shortcuts

### ISSUE THREAD

**Issue by alanehill** [acristoffers/gnome-rectangle#4] opened 2024-05-12 05:31 UTC
There's a subtle bug in the Shortcuts tab of the preferences window.

To reproduce:
Set Maximize to Ctrl+G
Set Almost Maximize to Ctrl+Shift+G

Instead of setting the second shortcut, nothing happens. I can't seem to set a shortcut if it's similar to an existing one, but just uses more modifiers. So in the above example, I could set the first to Ctrl+G and the second to Ctrl+Shift+H. But if I try to set the first to Ctrl+G and the second to Ctrl+Shift+G the second will fail because it's like the first plus the shift key.

What *does* work is if you reverse the order: set Almost Maximize to Ctrl+Shift+G, then set Maximize to Ctrl+G. That works, because it's only a problem when you try to set a similar shortcut with *more* modifiers, not fewer.

**Comment by acristoffers** [comment] 2024-05-12 07:52
It works for me in 3 machines (NixOS unstable, Fedora 40 and Ubuntu 24.04). Also, your choice of shortcut is very likely to conflict with applications' shortcuts. For instance, `ctrl+g` and `ctrl+shift+g` are used by Firefox to go to next/previous search result. What OS and version of Gnome are you on?

**Comment by scadu** [comment] 2024-09-02 15:57
> It works for me in 3 machines (NixOS unstable, Fedora 40 and Ubuntu 24.04). Also, your choice of shortcut is very likely to conflict with applications' shortcuts. For instance, `ctrl+g` and `ctrl+shift+g` are used by Firefox to go to next/previous search result. What OS and version of Gnome are you on?

In my case I cannot set a new shortcut when the same combination is already used for different action. Newest version of the plugin published to the https://extensions.gnome.org, GNOME 46.

**Comment by acristoffers** [comment] 2024-09-06 19:13
That's just how GNOME works. I tried setting a shortcut in another extension to something that already exists and it doesn't work there either. Not even the settings app does overriding. If you know of an extension that does that, I can see what they do and try to replicate, but AFAIK it is not possible to override someone else's bindings.

**Comment by rstacruz** [comment] 2024-09-07 07:21
I got GNOME 46 on Arch Linux, unfortunately I'm not able to reproduce this issue either.

**Comment by acristoffers** [comment] 2024-11-30 20:33
I'm closing it since I cannot reproduce and it has been a while since it was opened.

**Closed as completed by acristoffers** 2024-11-30 20:33 UTC
